/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  AuditLogRead,
  GetAllAuditLogsGetParams,
  HTTPValidationError,
} from "../index.schemas";

/**
 * Global Audit Trail (AUDIT-004).
Only Admins should see the full system history.
 * @summary Get All Audit Logs
 */
export const getAllAuditLogsGet = (
  params?: GetAllAuditLogsGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AuditLogRead[]>> => {
  return axios.get(`/`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetAllAuditLogsGetQueryKey = (
  params?: GetAllAuditLogsGetParams,
) => {
  return [`/`, ...(params ? [params] : [])] as const;
};

export const getGetAllAuditLogsGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllAuditLogsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetAllAuditLogsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllAuditLogsGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllAuditLogsGet>>
  > = ({ signal }) => getAllAuditLogsGet(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllAuditLogsGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllAuditLogsGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllAuditLogsGet>>
>;
export type GetAllAuditLogsGetQueryError = AxiosError<HTTPValidationError>;

export function useGetAllAuditLogsGet<
  TData = Awaited<ReturnType<typeof getAllAuditLogsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: undefined | GetAllAuditLogsGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllAuditLogsGet>>,
          TError,
          Awaited<ReturnType<typeof getAllAuditLogsGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllAuditLogsGet<
  TData = Awaited<ReturnType<typeof getAllAuditLogsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetAllAuditLogsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllAuditLogsGet>>,
          TError,
          Awaited<ReturnType<typeof getAllAuditLogsGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllAuditLogsGet<
  TData = Awaited<ReturnType<typeof getAllAuditLogsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetAllAuditLogsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get All Audit Logs
 */

export function useGetAllAuditLogsGet<
  TData = Awaited<ReturnType<typeof getAllAuditLogsGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params?: GetAllAuditLogsGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllAuditLogsGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Specific history for a single Leave Request.
Contractors can see history of THEIR own requests.
Managers/Admins can see history of requests they have access to.
 * @summary Get Leave History
 */
export const getLeaveHistoryLeaveLeaveRequestIdGet = (
  leaveRequestId: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<AuditLogRead[]>> => {
  return axios.get(`/leave/${leaveRequestId}`, options);
};

export const getGetLeaveHistoryLeaveLeaveRequestIdGetQueryKey = (
  leaveRequestId?: number,
) => {
  return [`/leave/${leaveRequestId}`] as const;
};

export const getGetLeaveHistoryLeaveLeaveRequestIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveRequestId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetLeaveHistoryLeaveLeaveRequestIdGetQueryKey(leaveRequestId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>
  > = ({ signal }) =>
    getLeaveHistoryLeaveLeaveRequestIdGet(leaveRequestId, {
      signal,
      ...axiosOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!leaveRequestId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLeaveHistoryLeaveLeaveRequestIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>
>;
export type GetLeaveHistoryLeaveLeaveRequestIdGetQueryError =
  AxiosError<HTTPValidationError>;

export function useGetLeaveHistoryLeaveLeaveRequestIdGet<
  TData = Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveRequestId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaveHistoryLeaveLeaveRequestIdGet<
  TData = Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveRequestId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaveHistoryLeaveLeaveRequestIdGet<
  TData = Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveRequestId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Leave History
 */

export function useGetLeaveHistoryLeaveLeaveRequestIdGet<
  TData = Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveRequestId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLeaveHistoryLeaveLeaveRequestIdGetQueryOptions(
    leaveRequestId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
