/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuditLogRead,
  GetAllAuditLogsAuditGetParams,
  HTTPValidationError,
} from "../index.schemas";

import { customInstance } from ".././axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Global Audit Trail (AUDIT-004).
Only Admins should see the full system history.
 * @summary Get All Audit Logs
 */
export const getAllAuditLogsAuditGet = (
  params?: GetAllAuditLogsAuditGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuditLogRead[]>(
    { url: `/audit/`, method: "GET", params, signal },
    options,
  );
};

export const getGetAllAuditLogsAuditGetQueryKey = (
  params?: GetAllAuditLogsAuditGetParams,
) => {
  return [`/audit/`, ...(params ? [params] : [])] as const;
};

export const getGetAllAuditLogsAuditGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
  TError = HTTPValidationError,
>(
  params?: GetAllAuditLogsAuditGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllAuditLogsAuditGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>
  > = ({ signal }) => getAllAuditLogsAuditGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllAuditLogsAuditGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>
>;
export type GetAllAuditLogsAuditGetQueryError = HTTPValidationError;

export function useGetAllAuditLogsAuditGet<
  TData = Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
  TError = HTTPValidationError,
>(
  params: undefined | GetAllAuditLogsAuditGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
          TError,
          Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllAuditLogsAuditGet<
  TData = Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
  TError = HTTPValidationError,
>(
  params?: GetAllAuditLogsAuditGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
          TError,
          Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllAuditLogsAuditGet<
  TData = Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
  TError = HTTPValidationError,
>(
  params?: GetAllAuditLogsAuditGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get All Audit Logs
 */

export function useGetAllAuditLogsAuditGet<
  TData = Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
  TError = HTTPValidationError,
>(
  params?: GetAllAuditLogsAuditGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllAuditLogsAuditGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllAuditLogsAuditGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Specific history for a single Leave Request.
Contractors can see history of THEIR own requests.
Managers/Admins can see history of requests they have access to.
 * @summary Get Leave History
 */
export const getLeaveHistoryAuditLeaveLeaveRequestIdGet = (
  leaveRequestId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuditLogRead[]>(
    { url: `/audit/leave/${leaveRequestId}`, method: "GET", signal },
    options,
  );
};

export const getGetLeaveHistoryAuditLeaveLeaveRequestIdGetQueryKey = (
  leaveRequestId?: number,
) => {
  return [`/audit/leave/${leaveRequestId}`] as const;
};

export const getGetLeaveHistoryAuditLeaveLeaveRequestIdGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>
  >,
  TError = HTTPValidationError,
>(
  leaveRequestId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetLeaveHistoryAuditLeaveLeaveRequestIdGetQueryKey(leaveRequestId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>
  > = ({ signal }) =>
    getLeaveHistoryAuditLeaveLeaveRequestIdGet(
      leaveRequestId,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: !!leaveRequestId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLeaveHistoryAuditLeaveLeaveRequestIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>
>;
export type GetLeaveHistoryAuditLeaveLeaveRequestIdGetQueryError =
  HTTPValidationError;

export function useGetLeaveHistoryAuditLeaveLeaveRequestIdGet<
  TData = Awaited<
    ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>
  >,
  TError = HTTPValidationError,
>(
  leaveRequestId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>
          >,
          TError,
          Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaveHistoryAuditLeaveLeaveRequestIdGet<
  TData = Awaited<
    ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>
  >,
  TError = HTTPValidationError,
>(
  leaveRequestId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>
          >,
          TError,
          Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaveHistoryAuditLeaveLeaveRequestIdGet<
  TData = Awaited<
    ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>
  >,
  TError = HTTPValidationError,
>(
  leaveRequestId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Leave History
 */

export function useGetLeaveHistoryAuditLeaveLeaveRequestIdGet<
  TData = Awaited<
    ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>
  >,
  TError = HTTPValidationError,
>(
  leaveRequestId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveHistoryAuditLeaveLeaveRequestIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetLeaveHistoryAuditLeaveLeaveRequestIdGetQueryOptions(
      leaveRequestId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
