/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  HTTPValidationError,
  ListUsersUsersGetParams,
  UserRead,
  UserUpdateAdmin,
  UserUpdateSelf,
} from "../index.schemas";

import { customInstance } from ".././axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get Current User Profile
 */
export const getCurrentUserProfileUsersMeGet = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserRead>(
    { url: `/users/me`, method: "GET", signal },
    options,
  );
};

export const getGetCurrentUserProfileUsersMeGetQueryKey = () => {
  return [`/users/me`] as const;
};

export const getGetCurrentUserProfileUsersMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCurrentUserProfileUsersMeGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>
  > = ({ signal }) => getCurrentUserProfileUsersMeGet(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserProfileUsersMeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>
>;
export type GetCurrentUserProfileUsersMeGetQueryError = unknown;

export function useGetCurrentUserProfileUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUserProfileUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUserProfileUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Current User Profile
 */

export function useGetCurrentUserProfileUsersMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserProfileUsersMeGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCurrentUserProfileUsersMeGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update Current User Profile
 */
export const updateCurrentUserProfileUsersMePatch = (
  userUpdateSelf: UserUpdateSelf,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<UserRead>(
    {
      url: `/users/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: userUpdateSelf,
    },
    options,
  );
};

export const getUpdateCurrentUserProfileUsersMePatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCurrentUserProfileUsersMePatch>>,
    TError,
    { data: UserUpdateSelf },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCurrentUserProfileUsersMePatch>>,
  TError,
  { data: UserUpdateSelf },
  TContext
> => {
  const mutationKey = ["updateCurrentUserProfileUsersMePatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCurrentUserProfileUsersMePatch>>,
    { data: UserUpdateSelf }
  > = (props) => {
    const { data } = props ?? {};

    return updateCurrentUserProfileUsersMePatch(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCurrentUserProfileUsersMePatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCurrentUserProfileUsersMePatch>>
>;
export type UpdateCurrentUserProfileUsersMePatchMutationBody = UserUpdateSelf;
export type UpdateCurrentUserProfileUsersMePatchMutationError =
  HTTPValidationError;

/**
 * @summary Update Current User Profile
 */
export const useUpdateCurrentUserProfileUsersMePatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCurrentUserProfileUsersMePatch>>,
      TError,
      { data: UserUpdateSelf },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCurrentUserProfileUsersMePatch>>,
  TError,
  { data: UserUpdateSelf },
  TContext
> => {
  const mutationOptions =
    getUpdateCurrentUserProfileUsersMePatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List Users
 */
export const listUsersUsersGet = (
  params?: ListUsersUsersGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserRead[]>(
    { url: `/users/`, method: "GET", params, signal },
    options,
  );
};

export const getListUsersUsersGetQueryKey = (
  params?: ListUsersUsersGetParams,
) => {
  return [`/users/`, ...(params ? [params] : [])] as const;
};

export const getListUsersUsersGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listUsersUsersGet>>,
  TError = HTTPValidationError,
>(
  params?: ListUsersUsersGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUsersUsersGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListUsersUsersGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listUsersUsersGet>>
  > = ({ signal }) => listUsersUsersGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listUsersUsersGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListUsersUsersGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listUsersUsersGet>>
>;
export type ListUsersUsersGetQueryError = HTTPValidationError;

export function useListUsersUsersGet<
  TData = Awaited<ReturnType<typeof listUsersUsersGet>>,
  TError = HTTPValidationError,
>(
  params: undefined | ListUsersUsersGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUsersUsersGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof listUsersUsersGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListUsersUsersGet<
  TData = Awaited<ReturnType<typeof listUsersUsersGet>>,
  TError = HTTPValidationError,
>(
  params?: ListUsersUsersGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUsersUsersGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listUsersUsersGet>>,
          TError,
          Awaited<ReturnType<typeof listUsersUsersGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListUsersUsersGet<
  TData = Awaited<ReturnType<typeof listUsersUsersGet>>,
  TError = HTTPValidationError,
>(
  params?: ListUsersUsersGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUsersUsersGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Users
 */

export function useListUsersUsersGet<
  TData = Awaited<ReturnType<typeof listUsersUsersGet>>,
  TError = HTTPValidationError,
>(
  params?: ListUsersUsersGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listUsersUsersGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListUsersUsersGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get User By Id
 */
export const getUserByIdUsersUserIdGet = (
  userId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UserRead>(
    { url: `/users/${userId}`, method: "GET", signal },
    options,
  );
};

export const getGetUserByIdUsersUserIdGetQueryKey = (userId?: number) => {
  return [`/users/${userId}`] as const;
};

export const getGetUserByIdUsersUserIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
  TError = HTTPValidationError,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserByIdUsersUserIdGetQueryKey(userId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>
  > = ({ signal }) => getUserByIdUsersUserIdGet(userId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserByIdUsersUserIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>
>;
export type GetUserByIdUsersUserIdGetQueryError = HTTPValidationError;

export function useGetUserByIdUsersUserIdGet<
  TData = Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
  TError = HTTPValidationError,
>(
  userId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserByIdUsersUserIdGet<
  TData = Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
  TError = HTTPValidationError,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserByIdUsersUserIdGet<
  TData = Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
  TError = HTTPValidationError,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get User By Id
 */

export function useGetUserByIdUsersUserIdGet<
  TData = Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
  TError = HTTPValidationError,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUsersUserIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserByIdUsersUserIdGetQueryOptions(
    userId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update User Details
 */
export const updateUserDetailsUsersUserIdPatch = (
  userId: number,
  userUpdateAdmin: UserUpdateAdmin,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<UserRead>(
    {
      url: `/users/${userId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: userUpdateAdmin,
    },
    options,
  );
};

export const getUpdateUserDetailsUsersUserIdPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserDetailsUsersUserIdPatch>>,
    TError,
    { userId: number; data: UserUpdateAdmin },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserDetailsUsersUserIdPatch>>,
  TError,
  { userId: number; data: UserUpdateAdmin },
  TContext
> => {
  const mutationKey = ["updateUserDetailsUsersUserIdPatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserDetailsUsersUserIdPatch>>,
    { userId: number; data: UserUpdateAdmin }
  > = (props) => {
    const { userId, data } = props ?? {};

    return updateUserDetailsUsersUserIdPatch(userId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserDetailsUsersUserIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserDetailsUsersUserIdPatch>>
>;
export type UpdateUserDetailsUsersUserIdPatchMutationBody = UserUpdateAdmin;
export type UpdateUserDetailsUsersUserIdPatchMutationError =
  HTTPValidationError;

/**
 * @summary Update User Details
 */
export const useUpdateUserDetailsUsersUserIdPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserDetailsUsersUserIdPatch>>,
      TError,
      { userId: number; data: UserUpdateAdmin },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserDetailsUsersUserIdPatch>>,
  TError,
  { userId: number; data: UserUpdateAdmin },
  TContext
> => {
  const mutationOptions =
    getUpdateUserDetailsUsersUserIdPatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
