/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  HTTPValidationError,
  UserRead,
  UserUpdateAdmin,
  UserUpdateSelf,
} from "../index.schemas";

/**
 * @summary Get Current User Profile
 */
export const getCurrentUserProfileMeGet = (
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserRead>> => {
  return axios.get(`/me`, options);
};

export const getGetCurrentUserProfileMeGetQueryKey = () => {
  return [`/me`] as const;
};

export const getGetCurrentUserProfileMeGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
  TError = AxiosError<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
      TError,
      TData
    >
  >;
  axios?: AxiosRequestConfig;
}) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCurrentUserProfileMeGetQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>
  > = ({ signal }) => getCurrentUserProfileMeGet({ signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCurrentUserProfileMeGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>
>;
export type GetCurrentUserProfileMeGetQueryError = AxiosError<unknown>;

export function useGetCurrentUserProfileMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
  TError = AxiosError<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUserProfileMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCurrentUserProfileMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Current User Profile
 */

export function useGetCurrentUserProfileMeGet<
  TData = Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
  TError = AxiosError<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCurrentUserProfileMeGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCurrentUserProfileMeGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update Current User Profile
 */
export const updateCurrentUserProfileMePatch = (
  userUpdateSelf: UserUpdateSelf,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserRead>> => {
  return axios.patch(`/me`, userUpdateSelf, options);
};

export const getUpdateCurrentUserProfileMePatchMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateCurrentUserProfileMePatch>>,
    TError,
    { data: UserUpdateSelf },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateCurrentUserProfileMePatch>>,
  TError,
  { data: UserUpdateSelf },
  TContext
> => {
  const mutationKey = ["updateCurrentUserProfileMePatch"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateCurrentUserProfileMePatch>>,
    { data: UserUpdateSelf }
  > = (props) => {
    const { data } = props ?? {};

    return updateCurrentUserProfileMePatch(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateCurrentUserProfileMePatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateCurrentUserProfileMePatch>>
>;
export type UpdateCurrentUserProfileMePatchMutationBody = UserUpdateSelf;
export type UpdateCurrentUserProfileMePatchMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Update Current User Profile
 */
export const useUpdateCurrentUserProfileMePatch = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateCurrentUserProfileMePatch>>,
      TError,
      { data: UserUpdateSelf },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateCurrentUserProfileMePatch>>,
  TError,
  { data: UserUpdateSelf },
  TContext
> => {
  const mutationOptions =
    getUpdateCurrentUserProfileMePatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get User By Id
 */
export const getUserByIdUserIdGet = (
  userId: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserRead>> => {
  return axios.get(`/${userId}`, options);
};

export const getGetUserByIdUserIdGetQueryKey = (userId?: number) => {
  return [`/${userId}`] as const;
};

export const getGetUserByIdUserIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetUserByIdUserIdGetQueryKey(userId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUserByIdUserIdGet>>
  > = ({ signal }) => getUserByIdUserIdGet(userId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserByIdUserIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserByIdUserIdGet>>
>;
export type GetUserByIdUserIdGetQueryError = AxiosError<HTTPValidationError>;

export function useGetUserByIdUserIdGet<
  TData = Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  userId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserByIdUserIdGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserByIdUserIdGet<
  TData = Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
          TError,
          Awaited<ReturnType<typeof getUserByIdUserIdGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserByIdUserIdGet<
  TData = Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get User By Id
 */

export function useGetUserByIdUserIdGet<
  TData = Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  userId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getUserByIdUserIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserByIdUserIdGetQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update User Details
 */
export const updateUserDetailsUserIdPatch = (
  userId: number,
  userUpdateAdmin: UserUpdateAdmin,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserRead>> => {
  return axios.patch(`/${userId}`, userUpdateAdmin, options);
};

export const getUpdateUserDetailsUserIdPatchMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserDetailsUserIdPatch>>,
    TError,
    { userId: number; data: UserUpdateAdmin },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserDetailsUserIdPatch>>,
  TError,
  { userId: number; data: UserUpdateAdmin },
  TContext
> => {
  const mutationKey = ["updateUserDetailsUserIdPatch"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserDetailsUserIdPatch>>,
    { userId: number; data: UserUpdateAdmin }
  > = (props) => {
    const { userId, data } = props ?? {};

    return updateUserDetailsUserIdPatch(userId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserDetailsUserIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserDetailsUserIdPatch>>
>;
export type UpdateUserDetailsUserIdPatchMutationBody = UserUpdateAdmin;
export type UpdateUserDetailsUserIdPatchMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Update User Details
 */
export const useUpdateUserDetailsUserIdPatch = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserDetailsUserIdPatch>>,
      TError,
      { userId: number; data: UserUpdateAdmin },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserDetailsUserIdPatch>>,
  TError,
  { userId: number; data: UserUpdateAdmin },
  TContext
> => {
  const mutationOptions =
    getUpdateUserDetailsUserIdPatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
