"""Sync models: add document table and update user/auditlog

Revision ID: fdc508f3d34b
Revises: 536dbe85e1ed
Create Date: 2025-12-21 13:25:17.026094

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'fdc508f3d34b'
down_revision = '536dbe85e1ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'leave_request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('user', sa.Column('department', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('manager_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_department'), 'user', ['department'], unique=False)
    op.create_foreign_key(None, 'user', 'user', ['manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_department'), table_name='user')
    op.drop_column('user', 'manager_id')
    op.drop_column('user', 'department')
    op.alter_column('audit_log', 'leave_request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
