/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ExportReconciliationCsvFinanceExportGetParams,
  FinanceSummary,
  GetMonthlyReconciliationFinanceReconciliationGetParams,
  HTTPValidationError,
} from "../index.schemas";

import { customInstance } from ".././axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Dashboard View: Returns JSON data for the frontend table.
 * @summary Get Monthly Reconciliation
 */
export const getMonthlyReconciliationFinanceReconciliationGet = (
  params: GetMonthlyReconciliationFinanceReconciliationGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<FinanceSummary>(
    { url: `/finance/reconciliation`, method: "GET", params, signal },
    options,
  );
};

export const getGetMonthlyReconciliationFinanceReconciliationGetQueryKey = (
  params?: GetMonthlyReconciliationFinanceReconciliationGetParams,
) => {
  return [`/finance/reconciliation`, ...(params ? [params] : [])] as const;
};

export const getGetMonthlyReconciliationFinanceReconciliationGetQueryOptions = <
  TData = Awaited<
    ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
  >,
  TError = HTTPValidationError,
>(
  params: GetMonthlyReconciliationFinanceReconciliationGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetMonthlyReconciliationFinanceReconciliationGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>>
  > = ({ signal }) =>
    getMonthlyReconciliationFinanceReconciliationGet(
      params,
      requestOptions,
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<
      ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
    >,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMonthlyReconciliationFinanceReconciliationGetQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>>
  >;
export type GetMonthlyReconciliationFinanceReconciliationGetQueryError =
  HTTPValidationError;

export function useGetMonthlyReconciliationFinanceReconciliationGet<
  TData = Awaited<
    ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
  >,
  TError = HTTPValidationError,
>(
  params: GetMonthlyReconciliationFinanceReconciliationGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMonthlyReconciliationFinanceReconciliationGet<
  TData = Awaited<
    ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
  >,
  TError = HTTPValidationError,
>(
  params: GetMonthlyReconciliationFinanceReconciliationGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
          >,
          TError,
          Awaited<
            ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMonthlyReconciliationFinanceReconciliationGet<
  TData = Awaited<
    ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
  >,
  TError = HTTPValidationError,
>(
  params: GetMonthlyReconciliationFinanceReconciliationGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Monthly Reconciliation
 */

export function useGetMonthlyReconciliationFinanceReconciliationGet<
  TData = Awaited<
    ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
  >,
  TError = HTTPValidationError,
>(
  params: GetMonthlyReconciliationFinanceReconciliationGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof getMonthlyReconciliationFinanceReconciliationGet>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getGetMonthlyReconciliationFinanceReconciliationGetQueryOptions(
      params,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Download Action: Streams a CSV file directly to the browser.
Essential for Finance Officers who love Excel.
 * @summary Export Reconciliation Csv
 */
export const exportReconciliationCsvFinanceExportGet = (
  params: ExportReconciliationCsvFinanceExportGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/finance/export`, method: "GET", params, signal },
    options,
  );
};

export const getExportReconciliationCsvFinanceExportGetQueryKey = (
  params?: ExportReconciliationCsvFinanceExportGetParams,
) => {
  return [`/finance/export`, ...(params ? [params] : [])] as const;
};

export const getExportReconciliationCsvFinanceExportGetQueryOptions = <
  TData = Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
  TError = HTTPValidationError,
>(
  params: ExportReconciliationCsvFinanceExportGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getExportReconciliationCsvFinanceExportGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>
  > = ({ signal }) =>
    exportReconciliationCsvFinanceExportGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExportReconciliationCsvFinanceExportGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>
>;
export type ExportReconciliationCsvFinanceExportGetQueryError =
  HTTPValidationError;

export function useExportReconciliationCsvFinanceExportGet<
  TData = Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
  TError = HTTPValidationError,
>(
  params: ExportReconciliationCsvFinanceExportGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportReconciliationCsvFinanceExportGet<
  TData = Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
  TError = HTTPValidationError,
>(
  params: ExportReconciliationCsvFinanceExportGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportReconciliationCsvFinanceExportGet<
  TData = Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
  TError = HTTPValidationError,
>(
  params: ExportReconciliationCsvFinanceExportGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Export Reconciliation Csv
 */

export function useExportReconciliationCsvFinanceExportGet<
  TData = Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
  TError = HTTPValidationError,
>(
  params: ExportReconciliationCsvFinanceExportGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvFinanceExportGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExportReconciliationCsvFinanceExportGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
