/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  ExportReconciliationCsvExportGetParams,
  FinanceSummary,
  GetMonthlyReconciliationReconciliationGetParams,
  HTTPValidationError,
} from "../index.schemas";

/**
 * Dashboard View: Returns JSON data for the frontend table.
 * @summary Get Monthly Reconciliation
 */
export const getMonthlyReconciliationReconciliationGet = (
  params: GetMonthlyReconciliationReconciliationGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<FinanceSummary>> => {
  return axios.get(`/reconciliation`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetMonthlyReconciliationReconciliationGetQueryKey = (
  params?: GetMonthlyReconciliationReconciliationGetParams,
) => {
  return [`/reconciliation`, ...(params ? [params] : [])] as const;
};

export const getGetMonthlyReconciliationReconciliationGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetMonthlyReconciliationReconciliationGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetMonthlyReconciliationReconciliationGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>
  > = ({ signal }) =>
    getMonthlyReconciliationReconciliationGet(params, {
      signal,
      ...axiosOptions,
    });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMonthlyReconciliationReconciliationGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>
>;
export type GetMonthlyReconciliationReconciliationGetQueryError =
  AxiosError<HTTPValidationError>;

export function useGetMonthlyReconciliationReconciliationGet<
  TData = Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetMonthlyReconciliationReconciliationGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
          TError,
          Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMonthlyReconciliationReconciliationGet<
  TData = Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetMonthlyReconciliationReconciliationGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
          TError,
          Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMonthlyReconciliationReconciliationGet<
  TData = Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetMonthlyReconciliationReconciliationGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Monthly Reconciliation
 */

export function useGetMonthlyReconciliationReconciliationGet<
  TData = Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: GetMonthlyReconciliationReconciliationGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMonthlyReconciliationReconciliationGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMonthlyReconciliationReconciliationGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Download Action: Streams a CSV file directly to the browser.
Essential for Finance Officers who love Excel.
 * @summary Export Reconciliation Csv
 */
export const exportReconciliationCsvExportGet = (
  params: ExportReconciliationCsvExportGetParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<unknown>> => {
  return axios.get(`/export`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getExportReconciliationCsvExportGetQueryKey = (
  params?: ExportReconciliationCsvExportGetParams,
) => {
  return [`/export`, ...(params ? [params] : [])] as const;
};

export const getExportReconciliationCsvExportGetQueryOptions = <
  TData = Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: ExportReconciliationCsvExportGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getExportReconciliationCsvExportGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>
  > = ({ signal }) =>
    exportReconciliationCsvExportGet(params, { signal, ...axiosOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExportReconciliationCsvExportGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>
>;
export type ExportReconciliationCsvExportGetQueryError =
  AxiosError<HTTPValidationError>;

export function useExportReconciliationCsvExportGet<
  TData = Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: ExportReconciliationCsvExportGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportReconciliationCsvExportGet<
  TData = Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: ExportReconciliationCsvExportGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useExportReconciliationCsvExportGet<
  TData = Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: ExportReconciliationCsvExportGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Export Reconciliation Csv
 */

export function useExportReconciliationCsvExportGet<
  TData = Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  params: ExportReconciliationCsvExportGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof exportReconciliationCsvExportGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getExportReconciliationCsvExportGetQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
