/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
/**
 * Minimal user info for the log view
 */
export interface AuditLogActorRead {
  id: number;
  full_name: string;
  email: string;
  role: UserRole;
}

export type AuditLogReadFieldChanged = string | null;

export type AuditLogReadOldValue = string | null;

export type AuditLogReadNewValue = string | null;

/**
 * The shape of the data sent to the Frontend.
We nest the 'actor' so the UI can display names immediately.
 */
export interface AuditLogRead {
  id: number;
  leave_request_id: number;
  action: string;
  field_changed: AuditLogReadFieldChanged;
  old_value: AuditLogReadOldValue;
  new_value: AuditLogReadNewValue;
  timestamp: string;
  actor: AuditLogActorRead;
}

export type FinanceReportRowVendorId = number | null;

/**
 * The Data shape for the UI Table (React/TanStack Table).
 */
export interface FinanceReportRow {
  user_id: number;
  full_name: string;
  vendor_id: FinanceReportRowVendorId;
  total_working_days: number;
  days_worked: number;
  chargeable_leave: number;
  non_chargeable_leave: number;
  total_billable_days: number;
}

export interface FinanceSummary {
  report_month: string;
  total_invoice_amount: number;
  rows: FinanceReportRow[];
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export type LeaveCategoryId = number | null;

/**
 * Configuration table. Changing 'is_chargeable' here affects FUTURE requests,
but not historical ones (due to snapshotting in LeaveRequest).
 */
export interface LeaveCategory {
  id?: LeaveCategoryId;
  name: string;
  /** If True, Government pays Vendor for this day */
  is_chargeable?: boolean;
}

export type LeaveRequestCreateAttachmentUrl = string | null;

/**
 * Safe Input: No status, no flags, just request data.
 */
export interface LeaveRequestCreate {
  category_id: number;
  start_date: string;
  end_date: string;
  total_days: number;
  reason: string;
  attachment_url?: LeaveRequestCreateAttachmentUrl;
}

export type LeaveRequestReadReason = string | null;

export type LeaveRequestReadAttachmentUrl = string | null;

export type LeaveRequestReadApprovedAt = string | null;

export type LeaveRequestReadCategory = LeaveCategory | null;

export type LeaveRequestReadUser = User | null;

/**
 * Output: Includes nested Category and User details for the UI.
 */
export interface LeaveRequestRead {
  id: number;
  user_id: number;
  category_id: number;
  start_date: string;
  end_date: string;
  total_days: number;
  status: LeaveStatus;
  cached_chargeable_status: boolean;
  reason?: LeaveRequestReadReason;
  attachment_url?: LeaveRequestReadAttachmentUrl;
  created_at: string;
  approved_at?: LeaveRequestReadApprovedAt;
  category?: LeaveRequestReadCategory;
  user?: LeaveRequestReadUser;
}

export type LeaveRequestUpdateStartDate = string | null;

export type LeaveRequestUpdateEndDate = string | null;

export type LeaveRequestUpdateTotalDays = number | null;

export type LeaveRequestUpdateReason = string | null;

export type LeaveRequestUpdateAttachmentUrl = string | null;

/**
 * Fields a user can change while it's still PENDING.
 */
export interface LeaveRequestUpdate {
  start_date?: LeaveRequestUpdateStartDate;
  end_date?: LeaveRequestUpdateEndDate;
  total_days?: LeaveRequestUpdateTotalDays;
  reason?: LeaveRequestUpdateReason;
  attachment_url?: LeaveRequestUpdateAttachmentUrl;
}

export type LeaveStatus = (typeof LeaveStatus)[keyof typeof LeaveStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LeaveStatus = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
} as const;

export type UserId = number | null;

/**
 * Vendor Company ID for billing grouping
 */
export type UserVendorId = number | null;

/**
 * Shadow User Table. 
'clerk_id' maps to the Authentication provider.
'id' is used for internal database foreign keys (Performance).
 */
export interface User {
  id?: UserId;
  clerk_id: string;
  email: string;
  full_name: string;
  role?: UserRole;
  /** Vendor Company ID for billing grouping */
  vendor_id?: UserVendorId;
}

export type UserReadVendorId = number | null;

/**
 * Public User profile
 */
export interface UserRead {
  id: number;
  clerk_id: string;
  email: string;
  full_name: string;
  role: UserRole;
  vendor_id?: UserReadVendorId;
}

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRole = {
  CONTRACTOR: "CONTRACTOR",
  MANAGER: "MANAGER",
  ADMIN: "ADMIN",
} as const;

export type UserUpdateAdminRole = UserRole | null;

export type UserUpdateAdminVendorId = number | null;

export type UserUpdateAdminFullName = string | null;

export type UserUpdateAdminIsActive = boolean | null;

/**
 * Fields an Admin can update on other users
 */
export interface UserUpdateAdmin {
  role?: UserUpdateAdminRole;
  vendor_id?: UserUpdateAdminVendorId;
  full_name?: UserUpdateAdminFullName;
  is_active?: UserUpdateAdminIsActive;
}

export type UserUpdateSelfFullName = string | null;

/**
 * Fields a user can update about themselves
 */
export interface UserUpdateSelf {
  full_name?: UserUpdateSelfFullName;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetAllAuditLogsGetParams = {
  offset?: number;
  /**
   * @maximum 100
   */
  limit?: number;
  user_id?: number | null;
  leave_id?: number | null;
};

export type ProcessLeaveStatusLeaveIdProcessPostParams = {
  status: LeaveStatus;
};

export type GetMonthlyReconciliationReconciliationGetParams = {
  year: number;
  month: number;
  /**
   * Potential working days in this month
   */
  working_days?: number;
};

export type ExportReconciliationCsvExportGetParams = {
  year: number;
  month: number;
  working_days?: number;
};
