/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  HTTPValidationError,
  LeaveRequestCreate,
  LeaveRequestRead,
  LeaveRequestUpdate,
  ProcessLeaveStatusLeaveIdProcessPostParams,
} from "../index.schemas";

/**
 * @summary Create Leave Request
 */
export const createLeaveRequestPost = (
  leaveRequestCreate: LeaveRequestCreate,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LeaveRequestRead>> => {
  return axios.post(`/`, leaveRequestCreate, options);
};

export const getCreateLeaveRequestPostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLeaveRequestPost>>,
    TError,
    { data: LeaveRequestCreate },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLeaveRequestPost>>,
  TError,
  { data: LeaveRequestCreate },
  TContext
> => {
  const mutationKey = ["createLeaveRequestPost"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLeaveRequestPost>>,
    { data: LeaveRequestCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createLeaveRequestPost(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLeaveRequestPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLeaveRequestPost>>
>;
export type CreateLeaveRequestPostMutationBody = LeaveRequestCreate;
export type CreateLeaveRequestPostMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Create Leave Request
 */
export const useCreateLeaveRequestPost = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLeaveRequestPost>>,
      TError,
      { data: LeaveRequestCreate },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createLeaveRequestPost>>,
  TError,
  { data: LeaveRequestCreate },
  TContext
> => {
  const mutationOptions = getCreateLeaveRequestPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Get Leave Detail
 */
export const getLeaveDetailLeaveIdGet = (
  leaveId: number,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LeaveRequestRead>> => {
  return axios.get(`/${leaveId}`, options);
};

export const getGetLeaveDetailLeaveIdGetQueryKey = (leaveId?: number) => {
  return [`/${leaveId}`] as const;
};

export const getGetLeaveDetailLeaveIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetLeaveDetailLeaveIdGetQueryKey(leaveId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>
  > = ({ signal }) =>
    getLeaveDetailLeaveIdGet(leaveId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!leaveId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLeaveDetailLeaveIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>
>;
export type GetLeaveDetailLeaveIdGetQueryError =
  AxiosError<HTTPValidationError>;

export function useGetLeaveDetailLeaveIdGet<
  TData = Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaveDetailLeaveIdGet<
  TData = Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaveDetailLeaveIdGet<
  TData = Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Leave Detail
 */

export function useGetLeaveDetailLeaveIdGet<
  TData = Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
  TError = AxiosError<HTTPValidationError>,
>(
  leaveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeaveIdGet>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLeaveDetailLeaveIdGetQueryOptions(
    leaveId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update Leave Request
 */
export const updateLeaveRequestLeaveIdPatch = (
  leaveId: number,
  leaveRequestUpdate: LeaveRequestUpdate,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LeaveRequestRead>> => {
  return axios.patch(`/${leaveId}`, leaveRequestUpdate, options);
};

export const getUpdateLeaveRequestLeaveIdPatchMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLeaveRequestLeaveIdPatch>>,
    TError,
    { leaveId: number; data: LeaveRequestUpdate },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateLeaveRequestLeaveIdPatch>>,
  TError,
  { leaveId: number; data: LeaveRequestUpdate },
  TContext
> => {
  const mutationKey = ["updateLeaveRequestLeaveIdPatch"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateLeaveRequestLeaveIdPatch>>,
    { leaveId: number; data: LeaveRequestUpdate }
  > = (props) => {
    const { leaveId, data } = props ?? {};

    return updateLeaveRequestLeaveIdPatch(leaveId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateLeaveRequestLeaveIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateLeaveRequestLeaveIdPatch>>
>;
export type UpdateLeaveRequestLeaveIdPatchMutationBody = LeaveRequestUpdate;
export type UpdateLeaveRequestLeaveIdPatchMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Update Leave Request
 */
export const useUpdateLeaveRequestLeaveIdPatch = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateLeaveRequestLeaveIdPatch>>,
      TError,
      { leaveId: number; data: LeaveRequestUpdate },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateLeaveRequestLeaveIdPatch>>,
  TError,
  { leaveId: number; data: LeaveRequestUpdate },
  TContext
> => {
  const mutationOptions =
    getUpdateLeaveRequestLeaveIdPatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Managers use this to Approve/Reject.
Triggers external sync if Approved.
 * @summary Process Leave Status
 */
export const processLeaveStatusLeaveIdProcessPost = (
  leaveId: number,
  params: ProcessLeaveStatusLeaveIdProcessPostParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<LeaveRequestRead>> => {
  return axios.post(`/${leaveId}/process`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getProcessLeaveStatusLeaveIdProcessPostMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof processLeaveStatusLeaveIdProcessPost>>,
    TError,
    { leaveId: number; params: ProcessLeaveStatusLeaveIdProcessPostParams },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof processLeaveStatusLeaveIdProcessPost>>,
  TError,
  { leaveId: number; params: ProcessLeaveStatusLeaveIdProcessPostParams },
  TContext
> => {
  const mutationKey = ["processLeaveStatusLeaveIdProcessPost"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof processLeaveStatusLeaveIdProcessPost>>,
    { leaveId: number; params: ProcessLeaveStatusLeaveIdProcessPostParams }
  > = (props) => {
    const { leaveId, params } = props ?? {};

    return processLeaveStatusLeaveIdProcessPost(leaveId, params, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProcessLeaveStatusLeaveIdProcessPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof processLeaveStatusLeaveIdProcessPost>>
>;

export type ProcessLeaveStatusLeaveIdProcessPostMutationError =
  AxiosError<HTTPValidationError>;

/**
 * @summary Process Leave Status
 */
export const useProcessLeaveStatusLeaveIdProcessPost = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof processLeaveStatusLeaveIdProcessPost>>,
      TError,
      { leaveId: number; params: ProcessLeaveStatusLeaveIdProcessPostParams },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof processLeaveStatusLeaveIdProcessPost>>,
  TError,
  { leaveId: number; params: ProcessLeaveStatusLeaveIdProcessPostParams },
  TContext
> => {
  const mutationOptions =
    getProcessLeaveStatusLeaveIdProcessPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
