/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Government Leave Portal API
 * Vibe Stack: FastAPI + SQLModel + Clerk + Orval
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BodyUploadDocumentLeavesLeaveIdUploadPost,
  DocumentRead,
  HTTPValidationError,
  LeaveRequestCreate,
  LeaveRequestRead,
  LeaveRequestUpdate,
  ListLeavesLeavesGetParams,
  ProcessLeaveStatusLeavesLeaveIdProcessPostParams,
} from "../index.schemas";

import { customInstance } from ".././axios-instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Create Leave Request
 */
export const createLeaveRequestLeavesPost = (
  leaveRequestCreate: LeaveRequestCreate,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LeaveRequestRead>(
    {
      url: `/leaves/`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: leaveRequestCreate,
      signal,
    },
    options,
  );
};

export const getCreateLeaveRequestLeavesPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createLeaveRequestLeavesPost>>,
    TError,
    { data: LeaveRequestCreate },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createLeaveRequestLeavesPost>>,
  TError,
  { data: LeaveRequestCreate },
  TContext
> => {
  const mutationKey = ["createLeaveRequestLeavesPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createLeaveRequestLeavesPost>>,
    { data: LeaveRequestCreate }
  > = (props) => {
    const { data } = props ?? {};

    return createLeaveRequestLeavesPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateLeaveRequestLeavesPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof createLeaveRequestLeavesPost>>
>;
export type CreateLeaveRequestLeavesPostMutationBody = LeaveRequestCreate;
export type CreateLeaveRequestLeavesPostMutationError = HTTPValidationError;

/**
 * @summary Create Leave Request
 */
export const useCreateLeaveRequestLeavesPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createLeaveRequestLeavesPost>>,
      TError,
      { data: LeaveRequestCreate },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createLeaveRequestLeavesPost>>,
  TError,
  { data: LeaveRequestCreate },
  TContext
> => {
  const mutationOptions =
    getCreateLeaveRequestLeavesPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary List Leaves
 */
export const listLeavesLeavesGet = (
  params?: ListLeavesLeavesGetParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LeaveRequestRead[]>(
    { url: `/leaves/`, method: "GET", params, signal },
    options,
  );
};

export const getListLeavesLeavesGetQueryKey = (
  params?: ListLeavesLeavesGetParams,
) => {
  return [`/leaves/`, ...(params ? [params] : [])] as const;
};

export const getListLeavesLeavesGetQueryOptions = <
  TData = Awaited<ReturnType<typeof listLeavesLeavesGet>>,
  TError = HTTPValidationError,
>(
  params?: ListLeavesLeavesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listLeavesLeavesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListLeavesLeavesGetQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listLeavesLeavesGet>>
  > = ({ signal }) => listLeavesLeavesGet(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listLeavesLeavesGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListLeavesLeavesGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof listLeavesLeavesGet>>
>;
export type ListLeavesLeavesGetQueryError = HTTPValidationError;

export function useListLeavesLeavesGet<
  TData = Awaited<ReturnType<typeof listLeavesLeavesGet>>,
  TError = HTTPValidationError,
>(
  params: undefined | ListLeavesLeavesGetParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listLeavesLeavesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLeavesLeavesGet>>,
          TError,
          Awaited<ReturnType<typeof listLeavesLeavesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListLeavesLeavesGet<
  TData = Awaited<ReturnType<typeof listLeavesLeavesGet>>,
  TError = HTTPValidationError,
>(
  params?: ListLeavesLeavesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listLeavesLeavesGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listLeavesLeavesGet>>,
          TError,
          Awaited<ReturnType<typeof listLeavesLeavesGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListLeavesLeavesGet<
  TData = Awaited<ReturnType<typeof listLeavesLeavesGet>>,
  TError = HTTPValidationError,
>(
  params?: ListLeavesLeavesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listLeavesLeavesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Leaves
 */

export function useListLeavesLeavesGet<
  TData = Awaited<ReturnType<typeof listLeavesLeavesGet>>,
  TError = HTTPValidationError,
>(
  params?: ListLeavesLeavesGetParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof listLeavesLeavesGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getListLeavesLeavesGetQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Get Leave Detail
 */
export const getLeaveDetailLeavesLeaveIdGet = (
  leaveId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LeaveRequestRead>(
    { url: `/leaves/${leaveId}`, method: "GET", signal },
    options,
  );
};

export const getGetLeaveDetailLeavesLeaveIdGetQueryKey = (leaveId?: number) => {
  return [`/leaves/${leaveId}`] as const;
};

export const getGetLeaveDetailLeavesLeaveIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
  TError = HTTPValidationError,
>(
  leaveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetLeaveDetailLeavesLeaveIdGetQueryKey(leaveId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>
  > = ({ signal }) =>
    getLeaveDetailLeavesLeaveIdGet(leaveId, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!leaveId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLeaveDetailLeavesLeaveIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>
>;
export type GetLeaveDetailLeavesLeaveIdGetQueryError = HTTPValidationError;

export function useGetLeaveDetailLeavesLeaveIdGet<
  TData = Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
  TError = HTTPValidationError,
>(
  leaveId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaveDetailLeavesLeaveIdGet<
  TData = Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
  TError = HTTPValidationError,
>(
  leaveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
          TError,
          Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLeaveDetailLeavesLeaveIdGet<
  TData = Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
  TError = HTTPValidationError,
>(
  leaveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Leave Detail
 */

export function useGetLeaveDetailLeavesLeaveIdGet<
  TData = Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
  TError = HTTPValidationError,
>(
  leaveId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLeaveDetailLeavesLeaveIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLeaveDetailLeavesLeaveIdGetQueryOptions(
    leaveId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary Update Leave Request
 */
export const updateLeaveRequestLeavesLeaveIdPatch = (
  leaveId: number,
  leaveRequestUpdate: LeaveRequestUpdate,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<LeaveRequestRead>(
    {
      url: `/leaves/${leaveId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: leaveRequestUpdate,
    },
    options,
  );
};

export const getUpdateLeaveRequestLeavesLeaveIdPatchMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateLeaveRequestLeavesLeaveIdPatch>>,
    TError,
    { leaveId: number; data: LeaveRequestUpdate },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateLeaveRequestLeavesLeaveIdPatch>>,
  TError,
  { leaveId: number; data: LeaveRequestUpdate },
  TContext
> => {
  const mutationKey = ["updateLeaveRequestLeavesLeaveIdPatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateLeaveRequestLeavesLeaveIdPatch>>,
    { leaveId: number; data: LeaveRequestUpdate }
  > = (props) => {
    const { leaveId, data } = props ?? {};

    return updateLeaveRequestLeavesLeaveIdPatch(leaveId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateLeaveRequestLeavesLeaveIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateLeaveRequestLeavesLeaveIdPatch>>
>;
export type UpdateLeaveRequestLeavesLeaveIdPatchMutationBody =
  LeaveRequestUpdate;
export type UpdateLeaveRequestLeavesLeaveIdPatchMutationError =
  HTTPValidationError;

/**
 * @summary Update Leave Request
 */
export const useUpdateLeaveRequestLeavesLeaveIdPatch = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateLeaveRequestLeavesLeaveIdPatch>>,
      TError,
      { leaveId: number; data: LeaveRequestUpdate },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateLeaveRequestLeavesLeaveIdPatch>>,
  TError,
  { leaveId: number; data: LeaveRequestUpdate },
  TContext
> => {
  const mutationOptions =
    getUpdateLeaveRequestLeavesLeaveIdPatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Managers use this to Approve/Reject.
Triggers external sync if Approved.
 * @summary Process Leave Status
 */
export const processLeaveStatusLeavesLeaveIdProcessPost = (
  leaveId: number,
  params: ProcessLeaveStatusLeavesLeaveIdProcessPostParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<LeaveRequestRead>(
    { url: `/leaves/${leaveId}/process`, method: "POST", params, signal },
    options,
  );
};

export const getProcessLeaveStatusLeavesLeaveIdProcessPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof processLeaveStatusLeavesLeaveIdProcessPost>>,
    TError,
    {
      leaveId: number;
      params: ProcessLeaveStatusLeavesLeaveIdProcessPostParams;
    },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof processLeaveStatusLeavesLeaveIdProcessPost>>,
  TError,
  { leaveId: number; params: ProcessLeaveStatusLeavesLeaveIdProcessPostParams },
  TContext
> => {
  const mutationKey = ["processLeaveStatusLeavesLeaveIdProcessPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof processLeaveStatusLeavesLeaveIdProcessPost>>,
    {
      leaveId: number;
      params: ProcessLeaveStatusLeavesLeaveIdProcessPostParams;
    }
  > = (props) => {
    const { leaveId, params } = props ?? {};

    return processLeaveStatusLeavesLeaveIdProcessPost(
      leaveId,
      params,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type ProcessLeaveStatusLeavesLeaveIdProcessPostMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof processLeaveStatusLeavesLeaveIdProcessPost>>
  >;

export type ProcessLeaveStatusLeavesLeaveIdProcessPostMutationError =
  HTTPValidationError;

/**
 * @summary Process Leave Status
 */
export const useProcessLeaveStatusLeavesLeaveIdProcessPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof processLeaveStatusLeavesLeaveIdProcessPost>>,
      TError,
      {
        leaveId: number;
        params: ProcessLeaveStatusLeavesLeaveIdProcessPostParams;
      },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof processLeaveStatusLeavesLeaveIdProcessPost>>,
  TError,
  { leaveId: number; params: ProcessLeaveStatusLeavesLeaveIdProcessPostParams },
  TContext
> => {
  const mutationOptions =
    getProcessLeaveStatusLeavesLeaveIdProcessPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Upload a file linked to a specific leave request.
 * @summary Upload Document
 */
export const uploadDocumentLeavesLeaveIdUploadPost = (
  leaveId: number,
  bodyUploadDocumentLeavesLeaveIdUploadPost: BodyUploadDocumentLeavesLeaveIdUploadPost,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, bodyUploadDocumentLeavesLeaveIdUploadPost.file);

  return customInstance<DocumentRead>(
    {
      url: `/leaves/${leaveId}/upload`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getUploadDocumentLeavesLeaveIdUploadPostMutationOptions = <
  TError = HTTPValidationError,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof uploadDocumentLeavesLeaveIdUploadPost>>,
    TError,
    { leaveId: number; data: BodyUploadDocumentLeavesLeaveIdUploadPost },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof uploadDocumentLeavesLeaveIdUploadPost>>,
  TError,
  { leaveId: number; data: BodyUploadDocumentLeavesLeaveIdUploadPost },
  TContext
> => {
  const mutationKey = ["uploadDocumentLeavesLeaveIdUploadPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof uploadDocumentLeavesLeaveIdUploadPost>>,
    { leaveId: number; data: BodyUploadDocumentLeavesLeaveIdUploadPost }
  > = (props) => {
    const { leaveId, data } = props ?? {};

    return uploadDocumentLeavesLeaveIdUploadPost(leaveId, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UploadDocumentLeavesLeaveIdUploadPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof uploadDocumentLeavesLeaveIdUploadPost>>
>;
export type UploadDocumentLeavesLeaveIdUploadPostMutationBody =
  BodyUploadDocumentLeavesLeaveIdUploadPost;
export type UploadDocumentLeavesLeaveIdUploadPostMutationError =
  HTTPValidationError;

/**
 * @summary Upload Document
 */
export const useUploadDocumentLeavesLeaveIdUploadPost = <
  TError = HTTPValidationError,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof uploadDocumentLeavesLeaveIdUploadPost>>,
      TError,
      { leaveId: number; data: BodyUploadDocumentLeavesLeaveIdUploadPost },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof uploadDocumentLeavesLeaveIdUploadPost>>,
  TError,
  { leaveId: number; data: BodyUploadDocumentLeavesLeaveIdUploadPost },
  TContext
> => {
  const mutationOptions =
    getUploadDocumentLeavesLeaveIdUploadPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary Download Document
 */
export const downloadDocumentLeavesDocumentsDocumentIdDownloadGet = (
  documentId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<unknown>(
    { url: `/leaves/documents/${documentId}/download`, method: "GET", signal },
    options,
  );
};

export const getDownloadDocumentLeavesDocumentsDocumentIdDownloadGetQueryKey = (
  documentId?: number,
) => {
  return [`/leaves/documents/${documentId}/download`] as const;
};

export const getDownloadDocumentLeavesDocumentsDocumentIdDownloadGetQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet>
    >,
    TError = HTTPValidationError,
  >(
    documentId: number,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<
              typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
            >
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof customInstance>;
    },
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getDownloadDocumentLeavesDocumentsDocumentIdDownloadGetQueryKey(
        documentId,
      );

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet>
      >
    > = ({ signal }) =>
      downloadDocumentLeavesDocumentsDocumentIdDownloadGet(
        documentId,
        requestOptions,
        signal,
      );

    return {
      queryKey,
      queryFn,
      enabled: !!documentId,
      ...queryOptions,
    } as UseQueryOptions<
      Awaited<
        ReturnType<typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet>
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type DownloadDocumentLeavesDocumentsDocumentIdDownloadGetQueryResult =
  NonNullable<
    Awaited<
      ReturnType<typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet>
    >
  >;
export type DownloadDocumentLeavesDocumentsDocumentIdDownloadGetQueryError =
  HTTPValidationError;

export function useDownloadDocumentLeavesDocumentsDocumentIdDownloadGet<
  TData = Awaited<
    ReturnType<typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet>
  >,
  TError = HTTPValidationError,
>(
  documentId: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownloadDocumentLeavesDocumentsDocumentIdDownloadGet<
  TData = Awaited<
    ReturnType<typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet>
  >,
  TError = HTTPValidationError,
>(
  documentId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
          >
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<
              typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
            >
          >,
          TError,
          Awaited<
            ReturnType<
              typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
            >
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDownloadDocumentLeavesDocumentsDocumentIdDownloadGet<
  TData = Awaited<
    ReturnType<typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet>
  >,
  TError = HTTPValidationError,
>(
  documentId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Download Document
 */

export function useDownloadDocumentLeavesDocumentsDocumentIdDownloadGet<
  TData = Awaited<
    ReturnType<typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet>
  >,
  TError = HTTPValidationError,
>(
  documentId: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<
            typeof downloadDocumentLeavesDocumentsDocumentIdDownloadGet
          >
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getDownloadDocumentLeavesDocumentsDocumentIdDownloadGetQueryOptions(
      documentId,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
